### ISSUE TITLE
Does not handle .xlsm files correctly

### ISSUE THREAD

**Issue by peteralbert** [amalanov/EditExcelPQM#5]
When I try to extract the M code from an .xslm file, I get an error message:

![Example](https://user-images.githubusercontent.com/2182870/99679315-16194c00-2a7c-11eb-99d3-b7c6de1428ba.gif)

**Comment by amalanov** [comment]
Hi, @peteralbert. Thanks. I'll fix it this weekend.

**Comment by amalanov** [comment]
@peteralbert , done in 1.1.5

**Comment by peteralbert** [comment]
Thanks a lot! Works now!

**Comment by amalanov** [comment]
@peteralbert , I'll be glad if you leave a rate and review on the vscode market.
